Data = read.csv("~/Downloads/StudentsPerformance.csv")
View(Data)
dim(Data)
head(Data)
mean(Data$math.score)
mean(Data$reading.score)
mean(Data$writing.score)
summary(Data)
write.csv(Data,"~/Documents/Students performance/Data Cleaning/clean data.csv")
Summary_data = summary(Data)
capture.output(Summary_data,file = "~/Documents/Students performance/Data Cleaning/Summary_Data.txt")